/**
 * JA4 TLS Fingerprint Extraction Middleware (Layer 3)
 *
 * JA4 is a TLS fingerprinting method that identifies the client's TLS
 * implementation by hashing fields from the ClientHello packet:
 *   - TLS protocol version
 *   - Cipher suites offered
 *   - Extensions
 *   - Elliptic curves
 *   - ALPN protocols
 *
 * Unlike browser JavaScript signals (Layer 1), the TLS ClientHello is
 * generated by the TLS library (BoringSSL, NSS, SChannel, etc.) and
 * cannot be modified by page JavaScript. This makes it a strong
 * cross-validation signal against User-Agent spoofing.
 *
 * Example JA4 hash: "t13d1516h2_8daaf6152771_e5627efa2ab1"
 *   t13 = TLS 1.3
 *   d1516h2 = cipher + extension profile
 *
 * Uses the `read-tls-client-hello` npm package (2M+ downloads/week) which
 * parses the raw TLS ClientHello bytes from the Node.js socket.
 *
 * Limitations in POC:
 *   - Only works when Express terminates TLS directly (not behind nginx/ALB)
 *   - In Docker dev mode (plain HTTP), socket.encrypted is false → req.ja4 = null
 *   - Production would extract JA4 from a reverse proxy header or edge function
 */

import { readTlsClientHello } from 'read-tls-client-hello';

/**
 * Express middleware — extracts JA4 hash from the TLS socket.
 *
 * Attaches `req.ja4` as { hash: string, raw: {...} } on success,
 * or `req.ja4 = null` on failure. Never blocks the request.
 *
 * Must be applied before route handlers that use JA4.
 * Applied globally in index.js.
 */
export function extractJa4(req, _res, next) {
  try {
    // Access the raw TCP socket from the HTTP request
    const socket = req.socket || req.connection;

    // Only attempt extraction on encrypted (TLS) connections
    if (!socket || !socket.encrypted) {
      req.ja4 = null;
      return next();
    }

    // Parse the TLS ClientHello from the raw socket bytes
    const hello = readTlsClientHello(socket);

    if (hello && hello.ja4) {
      // Store JA4 hash and raw parsed data for downstream use
      req.ja4 = {
        hash: hello.ja4,
        raw: {
          version: hello.version,
          ciphers: hello.ciphers,
          extensions: hello.extensions,
        },
      };
      console.log(`[ja4] extracted hash: ${hello.ja4}`);
    } else {
      req.ja4 = null;
      console.log('[ja4] extraction returned no hash');
    }
  } catch (err) {
    // Graceful degradation — don't break the request if JA4 fails
    req.ja4 = null;
    console.log(`[ja4] extraction failed: ${err.message}`);
  }

  next();
}
