/**
 * JA4 TLS Fingerprint Extraction Middleware (Layer 3)
 *
 * JA4 is a TLS fingerprinting method that identifies the client's TLS
 * implementation by hashing fields from the ClientHello packet:
 *   - TLS protocol version
 *   - Cipher suites offered
 *   - Extensions
 *   - Elliptic curves
 *   - ALPN protocols
 *
 * Unlike browser JavaScript signals (Layer 1), the TLS ClientHello is
 * generated by the TLS library (BoringSSL, NSS, SChannel, etc.) and
 * cannot be modified by page JavaScript. This makes it a strong
 * cross-validation signal against User-Agent spoofing.
 *
 * Example JA4 hash: "t13d1516h2_8daaf6152771_e5627efa2ab1"
 *   t13 = TLS 1.3
 *   d1516h2 = cipher + extension profile
 *
 * How it works: index.js applies `trackClientHellos(httpsServer)` from the
 * `read-tls-client-hello` package, which parses the raw ClientHello bytes
 * BEFORE the TLS handshake and attaches the result (including the JA4 hash)
 * to every socket as `socket.tlsClientHello`. This middleware only copies
 * that value to `req.ja4`.
 *
 * Limitations in POC:
 *   - Only works when Express terminates TLS directly (not behind nginx/ALB)
 *   - When the server falls back to plain HTTP (no openssl available),
 *     req.ja4 = null and the JA4 layer is disabled
 *   - Production would extract JA4 from a reverse proxy header or edge function
 */

import { logEvent } from '../log.js';

/**
 * Express middleware — copies the JA4 hash captured by trackClientHellos
 * from the TLS socket to `req.ja4` ({ hash } or null). Never blocks the request.
 */
export function extractJa4(req, _res, next) {
  const socket = req.socket;
  const hello = socket?.tlsClientHello;

  if (hello?.ja4) {
    req.ja4 = { hash: hello.ja4 };
    // Log once per socket (sockets are reused across keep-alive requests)
    if (!socket.ja4Logged) {
      socket.ja4Logged = true;
      logEvent('ja4.extracted', {
        ja4_hash: hello.ja4,
        user_agent: req.get('user-agent') || '',
      });
    }
  } else {
    req.ja4 = null;
    if (socket?.encrypted && !socket.ja4Logged) {
      socket.ja4Logged = true;
      logEvent('ja4.extraction_failed', { reason: 'no_client_hello_on_tls_socket' });
    }
  }

  next();
}
